### ISSUE TITLE
Modify 04. Loops.ipynb in order to reflect "correct" indexing order

### ISSUE THREAD

**Issue by julian-deltares** [JuliaComputing/JuliaBoxTutorials#52]
I think that https://github.com/JuliaComputing/JuliaBoxTutorials/blob/master/introductory-tutorials/intro-to-julia/04.%20Loops.ipynb should be adjusted to reverse the indexing order in the section *for loops*.

Maybe a brief note to the performance reasons behind this and a link to https://docs.julialang.org/en/v1/manual/performance-tips/#Access-arrays-in-memory-order,-along-columns-1 would be nice as well.

**Comment by NHDaly** [comment]
Makes sense to me. Could you please send a PR with that suggestion? :) Thanks!
